### ISSUE TITLE
Export CSV for Trades

### ISSUE THREAD

**Issue by nichtdu** [DeltaBalances/DeltaBalances.github.io#1]
Hey, 

do you plan to add an trade export as well in csv format? I saw you added balance csv lately

**Comment by DeltaBalances** [comment]
I do plan to add that, but I might first have to look into importing all trades. Otherwise you just export an incomplete history.
Right now its limited to taker orders as those are way easier to retrieve. Maker orders don't show up in you transactions and you have to scan all trades on the contract :(

**Comment by DeltaBalances** [comment]
I just added https://deltabalances.github.io/history.html
I'm still testing it, so it isn't linked anywhere yet, but I'd love some feedback.
