### ISSUE TITLE
Discrepancies with downloading events from blockchain

### ISSUE THREAD

**Issue by karjatu** [DeltaBalances/DeltaBalances.github.io#61]
1) I have recognized that I can download events on EtherDelta very fast from my both wallets by using https://deltabalances.github.io/recent.html , but the output does does not contain any MAKER trades, only TAKER trades making the report obsolete. (at least 50% of my trades have been maker trades)
2) I have recognized that I can use slower tool https://deltabalances.github.io/trades.html or https://deltabalances.github.io/history.html but instead of limited output the time range is limited and dependent of the wallet. relating to my Wallet A I can download all of events from June 2017, but relating to my wallet B I can download only data from Dec 2017. 
3) Conclusion: Recent.html is fast and bring all of data except MAKER trades. Trades.html or history.html is slow , but bring all of events including MAKER trades. Unfortunately all of time frames don't work and the accessible range of event is dependent on the wallet . The latter is very weird, because all of wallets should be similar within exception of different public ETH address. 

I need the event information of executed trades on Etherdelta for my tax reporting to government. 
What else: you are referring to Fork-delta. Based on my experience the upgraded original eEherdelta is much faster. You should add it to your tool.

**Comment by DeltaBalances** [comment]
The first part is by design:

- Recent.html is quick, it only checks incoming and outgoing transactions.  The other person makes the transaction on your maker order, therefore they can't be found here.
- trades.html/history.html  are slow and and check all events from completed trades on the exchange. It will find both maker & taker orders, but that takes quite a bit more time and effort.

The different timeframes per wallet sounds like a bug.
The possbile timeframe should only change when a different exchange is selected. For EtherDelta, anywhere from march 2017 until now should be possible. (block 3154196)

Can you try again with the different wallets, or maybe with a different browser?
I would love to get more details if this still occurs, as I'd like to fix any bugs showing up.

If you really can't get it to work, recently GammaDex (yet another site using the etherdelta contract) added a trade history too. They seem to cache everything on their server so it should be fairly quick.
https://gammadex.com/#!/history/

**Comment by karjatu** [comment]
Thank you for your reply. I reviewed my findings - Recent.html also showed my old ICO transactions as   trades. That caused an illusion of different time frames with different wallet address. There were three different event TAKER SELL, TAKER BUY and TRADE. Those TX that have marked as TRADEs were produced from my participation  in ICOs. I have not done any Etherdelta trades with that wallet before Dec 2017.  My situation with wallet A and B is less weird now
