### ISSUE TITLE
https://deltabalances.github.io/trades.html#0xbb827321a0382913a9ab3e3eaa965e5e5168c905

### ISSUE THREAD

**Issue by lotstep** [DeltaBalances/DeltaBalances.github.io#70]
Hello,
I would like to select my etherdelta trades for the wallet 0xbb827321a0382913a9ab3e3eaa965e5e5168c905 for june 2018.

I start and then the report runs into an endless loop: Loaded 2493/172527 blocks

No result !

Can you please check, regards

**Comment by DeltaBalances** [comment]
The source for the blockchain data (Infura) was returning some errors that I haven't encountered before.
Because of that the trades never loaded correctly.

I fixed that for now, and it also more clearly displays if something fails to load.
Let me know if it works.

And just in case, below is an export of the june 2018 for that wallet. 
 (format default V2, file extension changed from .csv to .txt to be able to attach it here.)
[EtherDelta_Trades_20190421_0xbb827321a0382913a9ab3e3eaa965e5e5168c905.txt](https://github.com/DeltaBalances/DeltaBalances.github.io/files/3100864/EtherDelta_Trades_20190421_0xbb827321a0382913a9ab3e3eaa965e5e5168c905.txt)
