### ISSUE TITLE
Point to Local Node

### ISSUE THREAD

**Issue by NoahMarconi** [DeltaBalances/DeltaBalances.github.io#78]
Seems Infura is rate limited hard right now. Scanning a single month or half a month fails.

I took a peek to see if it can point to a local node and see you have  https://github.com/DeltaBalances/DeltaBalances.github.io/blob/master/source/config.js#L89

but I don't see this actually consumed anywhere. Or toggle-able on the UI.

Short of cloning and hardcoding an override to the ethers provider init (https://github.com/DeltaBalances/DeltaBalances.github.io/blob/master/source/deltabalances.js#L20:L44) is there anyway to point to my own local node rather than be rate limited by infura?

A second place the infura connection is hardcoded is here: https://github.com/DeltaBalances/DeltaBalances.github.io/blob/bcdfd6c8053f67d5fa1613510d10f8c54022d815/source/utility.js#L707

I'm running a forked a modified version locally but it's a bit of a hackjob and I lose block timestamps on some records. Would be ideal to just point the public version to my rpc endpoint.

**Comment by DeltaBalances** [comment]
I add a source dropdown to the history pages.
The history code never got updated to ethers.js because it uses separate API keys due to the heavy volume.

It now gives the option for infura.io, rivet.cloud or localhost.
If you want to change these, the `historyUrls` array in config contains the values that populate it.

I haven't had a Geth node running for a while so the localhost option hasn't been tested. 
It tries the rpc endpoint for eth_getLogs on port 8545.

I might add a custom url entry later, that way you could use any private or public endpoint.
